/*
The Plaid API

The Plaid REST API. Please see https://plaid.com/docs/api for more details.

API version: 2020-09-14_1.64.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TransactionCode An identifier classifying the transaction type.  This field is only populated for European institutions. For institutions in the US and Canada, this field is set to `null`.  `adjustment:` Bank adjustment  `atm:` Cash deposit or withdrawal via an automated teller machine  `bank charge:` Charge or fee levied by the institution  `bill payment`: Payment of a bill  `cash:` Cash deposit or withdrawal  `cashback:` Cash withdrawal while making a debit card purchase  `cheque:` Document ordering the payment of money to another person or organization  `direct debit:` Automatic withdrawal of funds initiated by a third party at a regular interval  `interest:` Interest earned or incurred  `purchase:` Purchase made with a debit or credit card  `standing order:` Payment instructed by the account holder to a third party at a regular interval  `transfer:` Transfer of money between accounts
type TransactionCode string

// List of TransactionCode
const (
	ADJUSTMENT TransactionCode = "adjustment"
	ATM TransactionCode = "atm"
	BANK_CHARGE TransactionCode = "bank charge"
	BILL_PAYMENT TransactionCode = "bill payment"
	CASH TransactionCode = "cash"
	CASHBACK TransactionCode = "cashback"
	CHEQUE TransactionCode = "cheque"
	DIRECT_DEBIT TransactionCode = "direct debit"
	INTEREST TransactionCode = "interest"
	PURCHASE TransactionCode = "purchase"
	STANDING_ORDER TransactionCode = "standing order"
	TRANSFER TransactionCode = "transfer"
	NULL TransactionCode = "null"
)

// All allowed values of TransactionCode enum
var AllowedTransactionCodeEnumValues = []TransactionCode{
	"adjustment",
	"atm",
	"bank charge",
	"bill payment",
	"cash",
	"cashback",
	"cheque",
	"direct debit",
	"interest",
	"purchase",
	"standing order",
	"transfer",
	"null",
}

func (v *TransactionCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TransactionCode(value)
	for _, existing := range AllowedTransactionCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TransactionCode", value)
}

// NewTransactionCodeFromValue returns a pointer to a valid TransactionCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTransactionCodeFromValue(v string) (*TransactionCode, error) {
	ev := TransactionCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TransactionCode: valid values are %v", v, AllowedTransactionCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TransactionCode) IsValid() bool {
	for _, existing := range AllowedTransactionCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TransactionCode value
func (v TransactionCode) Ptr() *TransactionCode {
	return &v
}

type NullableTransactionCode struct {
	value *TransactionCode
	isSet bool
}

func (v NullableTransactionCode) Get() *TransactionCode {
	return v.value
}

func (v *NullableTransactionCode) Set(val *TransactionCode) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionCode) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionCode(val *TransactionCode) *NullableTransactionCode {
	return &NullableTransactionCode{value: val, isSet: true}
}

func (v NullableTransactionCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

